### ISSUE TITLE
[Windows 10] docker build for the ASP.NET Core project doesn't work, but dotnet publish command does

### ISSUE THREAD

**Issue by PatNeedham** [dawiddworak88/ASP.NET-Core-React-and-SSR#1]
I was about to post a question in a Docker forum but just as I was going to get a link to the `misc/docker` directory it disappeared, and I see that must be from the most recent commit. Here's what I was going to ask:

I was attempting to follow and run a sample application found at this repository. Originally I tried it on my Mac and the docker compose command worked perfectly fine, starting all 3 services. However when trying on my Windows work laptop it’s been an absolute nightmare. I’ve lost hours trying to figure out what’s causing it to fail on Windows, and believe it has to do with user permissions. The .NET Core app's `Dockerfile-dev` has a `RUN dotnet publish -c Release -o out` step, which works fine when running it directly on the Git Bash command line, but running `docker build -f Dockerfile-dev .` in that directory fails with this output:

```
Step 5/9 : RUN dotnet publish -c Release -o out
 ---> Running in c20e3f3e8110
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/3.1.102/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/app/AspNetCore.sln]
/usr/share/dotnet/sdk/3.1.102/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/app/AspNetCore.sln]
/usr/share/dotnet/sdk/3.1.102/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/app/AspNetCore.sln]
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

The front-end's `Dockerfile-ssr-dev` has a `chown -R node:node /home/node/aspnetcore-react-ssr` command, and I'm wondering does there need to be an equivalent for the backend? I'll try cloning down the latest and following the updated README steps to see if the original problem disappears

My Windows Docker version is 19.03.12

**Comment by dawiddworak88** [comment]
Hi @PatNeedham ,

yes, please check with the latest version. Make sure to download the latest stable Docker version. I'm using the Windows too, so let's get rid of the problem together.

Looking forward to hearing from you,

**Comment by PatNeedham** [comment]
I pulled the latest commit on the Windows machine, and the `npm install` step was causing problems but that only had to do with an internal registry being used (deleting `fe/package-lock.json` and reinstalling resolved it). However the `docker-compose -f ./be/src/docker-compose.yml up` command caused the npm install to time out - I saw a "Maximum call stack size exceeded" error when adding `--verbose` flag to that install step in `Dockerfile-ssr-dev`. Only tried doing the command line docker-compose because opening Visual Studio, setting the docker-compose as startup project and running that doesn't work. It starts the project but after a few seconds opens the browser to localhost:0 which comes up blank / "Can't reach this page" default browser error. Port 5000 and 5001 also result in the same.

Here are the AspNetCore container logs that appear in VS, I can't tell if there's any insight within them:
```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {205ffd3e-ad3b-474f-b04c-3b7102faee5b} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://[::]:443
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://[::]:443
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://[::]:443
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://[::]:443
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
```

Refreshing on ports 0, 5000, or 5001 don't cause any new rows to appear in those logs. And `docker_reat-ssr-web_1` container logs only have one row, `listening on 3000...`
